- name: variables from files
  hosts: local
  connection: local
  var_files:
  - course.yaml
  tasks: 
  - name: print course info 
    ansible.builtin.debug:
      msg: "course name is: {{ course }}, duration is {{ Duration }}, tainer is {{ Trainer }}"
