- name: check the facts
  hosts: local
  connection: local
  tasks:
  - name: install ngninx if redhat
    ansible.builtin.dnf:
      name: nginx
      state: latest 
    when: ansible_os_family == "Redhat"

