- name: fucntions
  hosts: local
  connection: local
  vars:
    techonologies: Devops, Linux, shell, ansible

    tags:
      Application: payment
      Environment: dev
  tasks:
  - name: default variables
    ansible.builtin.debug:
      msg: "Hello i am {{ name | default('suresh')}}"

  listTags:
  - key: Application
    value: payment
  - key: Environment
    value: dev    

  - name:
    ansible.builtin.debug:
      msg: "Techonology are: {{ techonologies | split(',')}}"

  - name: convert map to list
    ansible.builtin.debug:
      msg: "Tags: {{ tags | dict2items }}"



  - name: convert to map
    ansible.builtin.debug:
      msg: "Tag map: {{ listTags | items2dict }}"

